name: Build

on:
  push: # TODO: remove this
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  run-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install build tools
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: clang cmake ninja-build

      - name: Build project
        run: ./automated/build.sh
        shell: bash